---
apiVersion: v1
kind: Service
metadata:
  name: npuzzlex-frontend-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 80
  selector:
    name: npuzzlex-frontend